# Generated by Django 5.0.3 on 2024-03-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='udo_number',
            new_name='udo',
        ),
    ]
